---
- name: Garantir que o Samba esteja instalado
  ansible.builtin.apt:
    name: samba
    state: present
    update_cache: true

- name: Verificar usuários existentes no Samba
  ansible.builtin.command:
    cmd: "pdbedit -L -u {{ item.name }}"
  loop: "{{ homelab_users }}"
  register: samba_users_check
  changed_when: false
  failed_when: false

- name: Criar usuários no Samba
  ansible.builtin.command:
    cmd: "smbpasswd -a -s {{ item.item.name }}"
    stdin: "{{ samba_passwords[item.item.name] }}\n{{ samba_passwords[item.item.name] }}"
  loop: "{{ samba_users_check.results }}"
  when: item.rc != 0
  no_log: true

- name: Atualizar senhas dos usuários existentes no Samba
  ansible.builtin.command:
    cmd: "smbpasswd -s {{ item.item.name }}"
    stdin: "{{ samba_passwords[item.item.name] }}\n{{ samba_passwords[item.item.name] }}"
  loop: "{{ samba_users_check.results }}"
  when: item.rc == 0
  no_log: true

- name: Configurar Samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/bin/testparm -s %s"
  notify: Reiniciar Samba

- name: Garantir que o Samba esteja ativo
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true