---
- name: Garantir grupos do homelab
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ homelab_groups }}"

- name: Garantir usuários do homelab
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ '/bin/bash' if item.admin else '/usr/sbin/nologin' }}"
    create_home: "{{ item.admin }}"
    state: present
  loop: "{{ homelab_users }}"

- name: Garantir usuário de serviço
  ansible.builtin.user:
    name: "{{ homelab_service_user.name }}"
    group: "{{ homelab_service_user.group }}"
    shell: /usr/sbin/nologin
    create_home: false
    system: true
    password_lock: true
    state: present

- name: Sincronizar grupos dos usuários
  ansible.builtin.include_tasks: sync_user_groups.yml
  loop: "{{ homelab_users }}"
  loop_control:
    loop_var: homelab_user